---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aion-faucet-web
spec:
  replicas: 2
  selector:
    matchLabels:
      name: aion-faucet-web
  template:
    metadata:
      labels:
        name: aion-faucet-web
    spec:
      containers:
        - name: application
          image: bloxbean/aion-faucet-web:0.0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: mastery_operator_key
            valueFrom:
              secretKeyRef:
                name: aion-security
                key: mastery.operator.key
          - name: mastery_node_url
            valueFrom:
              secretKeyRef:
                name: aion-security
                key: mastery.node.url
          - name: amity_operator_key
            valueFrom:
              secretKeyRef:
                name: aion-security
                key: amity.operator.key
          - name: amity_node_url
            valueFrom:
              secretKeyRef:
                name: aion-security
                key: amity.node.url
          - name: redis_host
            value: "redis-master-ext"
          - name: redis_port
            value: "6379"