---
apiVersion: v1
kind: Service
metadata:
  name: aion-faucet-web-service
#  annotations:
#    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
#    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
#    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
spec:
  type: ClusterIP
#  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: aion-faucet-web